apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

patchesStrategicMerge:
 - deployment.yaml

images:
  - name: asia-northeast1-docker.pkg.dev/civil-campaign-244100/chanhu/chanhu-profile:latest

commonLabels:
  app.kubernetes.io/env: stg
  app.kubernetes.io/managed-by: kustomize

namespace: stg