apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

patchesStrategicMerge:
 - deployment.yaml

images:
  - name: nginx
    newTag: latest

commonLabels:
  app.kubernetes.io/env: stg
  app.kubernetes.io/managed-by: kustomize

namespace: stg