apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: myapp
        image: nginx:alpine
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name:  web-app-service
spec:
  selector:
    app: web-app
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80

---
#PreSyncのリソースHook
apiVersion: batch/v1
kind: Job
metadata:
  name: presync-job
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: presync
        image: ubuntu:latest
        command:
          - "/bin/bash"
        args:
          - "-c"
          - "date && echo 'presync' && sleep 60"
      restartPolicy: Never

---
#PostSyncのリソースHook
apiVersion: batch/v1
kind: Job
metadata:
  name: postsync-job
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: postsync
        image: ubuntu:latest
        command:
          - "/bin/bash"
        args:
          - "-c"
          - "date && echo 'postsync' && sleep 60"
      restartPolicy: Never